import type { Tx } from "@/lib/db"

// Config do agente de criação (Margot Editora) por tenant. Singleton na tabela
// editor_config (uma linha). Tenant-scoped (withTenant). Sem linha = defaults.

export type ContentFormat = "blog" | "linkedin" | "instagram"

export type EditorConfig = {
  system_prompt: string
  tone: string
  themes: string[]
  format: ContentFormat
  model: string | null
  enabled: boolean
  cadence_days: number
  /** Handle da marca no rodapé das peças de motion (ex.: @cliente). Vazio = default. */
  handle: string
}

const DEFAULTS: EditorConfig = {
  system_prompt: "",
  tone: "",
  themes: [],
  format: "blog",
  model: null,
  enabled: true,
  cadence_days: 7,
  handle: "",
}

export async function getEditorConfig(tx: Tx): Promise<EditorConfig> {
  const rows = (await tx`
    SELECT system_prompt, tone, themes, format, model, enabled, cadence_days, handle FROM editor_config WHERE id = true
  `) as unknown as {
    system_prompt: string
    tone: string
    themes: unknown
    format: string
    model: string | null
    enabled: boolean
    cadence_days: number
    handle: string | null
  }[]
  const r = rows[0]
  if (!r) return { ...DEFAULTS }
  const format: ContentFormat = r.format === "linkedin" || r.format === "instagram" ? r.format : "blog"
  return {
    system_prompt: r.system_prompt ?? "",
    tone: r.tone ?? "",
    themes: Array.isArray(r.themes) ? (r.themes as string[]) : [],
    format,
    model: r.model,
    enabled: r.enabled,
    cadence_days: r.cadence_days ?? 7,
    handle: r.handle ?? "",
  }
}

export async function upsertEditorConfig(tx: Tx, cfg: EditorConfig): Promise<void> {
  await tx`
    INSERT INTO editor_config (id, system_prompt, tone, themes, format, model, enabled, cadence_days, handle, updated_at)
    VALUES (true, ${cfg.system_prompt}, ${cfg.tone}, ${tx.json(cfg.themes)}, ${cfg.format}, ${cfg.model}, ${cfg.enabled}, ${cfg.cadence_days}, ${cfg.handle}, now())
    ON CONFLICT (id) DO UPDATE SET
      system_prompt = EXCLUDED.system_prompt,
      tone = EXCLUDED.tone,
      themes = EXCLUDED.themes,
      format = EXCLUDED.format,
      model = EXCLUDED.model,
      enabled = EXCLUDED.enabled,
      cadence_days = EXCLUDED.cadence_days,
      handle = EXCLUDED.handle,
      updated_at = now()
  `
}

/** Já passou o intervalo da cadência desde a última geração automática? (sem
 *  linha/nunca gerou = sim). Não considera o `enabled` — o cron checa isso à parte. */
export async function dueForAuto(tx: Tx, cadenceDays: number): Promise<boolean> {
  const rows = (await tx`
    SELECT (last_auto_at IS NULL OR now() - last_auto_at >= make_interval(days => ${cadenceDays})) AS due
      FROM editor_config WHERE id = true
  `) as unknown as { due: boolean }[]
  return rows[0]?.due ?? true
}

/** Marca a última geração automática = agora (cria a linha se não existir). */
export async function markAutoGenerated(tx: Tx): Promise<void> {
  await tx`
    INSERT INTO editor_config (id, last_auto_at) VALUES (true, now())
    ON CONFLICT (id) DO UPDATE SET last_auto_at = now()
  `
}
